export const strings = {
  app: 'leaf',
  loading: 'Загрузка…',
  projects: 'Проекты',
  newProject: 'Новый проект',
  projectTitle: 'Название проекта',
  createProject: 'Создать проект',
  noProjects: 'Создайте первый проект.',
  renameProject: 'Переименовать проект',
  logout: 'Выйти',
  login: 'Войти',
  password: 'Пароль',
  setup:
    'Аккаунт ещё не создан. Для локального запуска выполните make admin-setup в терминале из каталога проекта. Для Docker Compose выполните docker compose exec leaf npm run admin:setup на хосте. Задайте пароль и обновите страницу.',
  tasks: 'Задачи',
  taskFilters: 'Поиск и фильтры задач',
  searchTasks: 'Поиск задач',
  filterStatus: 'Фильтр по статусу',
  allStatuses: 'Все статусы',
  resetTaskFilters: 'Сбросить поиск и фильтры',
  reset: 'Сбросить',
  taskMatchCount: 'Найдено задач:',
  noTaskMatches: 'Ничего не найдено. Измените поиск или статус.',
  parentContext: 'Родительский контекст',
  context: 'Контекст',
  task: 'Задача',
  subtasks: 'Подзадачи',
  details: 'Детали',
  dependencies: 'Зависимости',
  planning: 'Планирование',
  projectActions: 'Действия проекта',
  closeProjectDialog: 'Закрыть',
  projectPlan: 'Настройки проекта',
  saveProjectPlan: 'Сохранить настройки проекта',
  projectStart: 'Начало проекта',
  calendar: 'Календарь',
  timezone: 'Часовой пояс проекта',
  mode: 'Режим планирования',
  duration: 'Длительность, рабочих дней',
  durationLabel: 'Длительность',
  durationWorkingDays: 'рабочих дней',
  days: 'дней',
  linkedPlanHint:
    'Поля необязательны. Начало и длительность меняют окончание; окончание меняет длительность. Расчёт после завершения ввода.',
  planInputError: 'Проверьте дату и длительность.',
  notBefore: 'Не раньше',
  deadline: 'Дедлайн',
  computedStart: 'Рассчитанное начало',
  computedFinish: 'Рассчитанное окончание',
  autoHint:
    'Начало рассчитывается по связям и «Не раньше». Изменение окончания меняет длительность.',
  fixedHint:
    'Обе границы закреплены. В календаре пн–пт они должны быть рабочими днями.',
  doneHint: 'Верните завершённую задачу в работу перед планированием.',
  fixedOffer: 'Закрепить интервал',
  clearPlan: 'Удалить планирование',
  clearPlanConfirm:
    'Удалить планирование? Связанные работы могут получить неполный расчёт. Изменение можно отменить.',
  workingDateError:
    'Выберите допустимое окончание не раньше начала; обе границы должны быть рабочими днями.',
  missingOrigin: 'Укажите начало проекта, чтобы увидеть календарный план.',
  coverage: 'Запланировано',
  of: 'из',
  leaves: 'конечных задач',
  preliminary: 'Предварительный расчёт',
  infeasible: 'Конфликт плана',
  critical: 'Критична для окончания проекта',
  criticalEdge: 'Критическая связь',
  partialCritical: 'Критична для датированной части',
  partialCriticalEdge: 'Критическая связь датированной части',
  partialContainsCritical: 'Содержит критические задачи датированной части',
  knownHorizonFloat: 'Резерв до известного горизонта',
  'scheduling.PARTIAL_ANALYSIS':
    'Анализ датированной части; полный критический путь неизвестен',
  unknownCritical: 'Полный критический путь неизвестен',
  readyCritical: 'Критический путь рассчитан',
  frozenPending: 'Сохранённый результат без расчёта критического пути',
  containsCritical: 'Содержит критические задачи',
  partial: 'Неполные сводные даты',
  projectFloat: 'Резерв проекта',
  constraintFloat: 'Резерв текущего размещения',
  workingDays: 'раб. дн.',
  notScheduled: 'Не запланировано',
  blocked: 'Расчёт заблокирован',
  gantt: 'Гант',
  scale: 'Масштаб Ганта',
  today: 'Сегодня',
  conditionalPlacement: 'Условное размещение; полный интервал не задан',
  newTaskSchedule: 'Сроки новой задачи',
  previousPeriod: 'Предыдущий период',
  nextPeriod: 'Следующий период',
  treeWidth: 'Ширина дерева',
  showOnGantt: 'Показать на Ганте',
  invalidGesture:
    'Недопустимая дата: проверьте рабочие дни, начало и окончание. План не изменён.',
  constrainedMove:
    'Начало осталось на допустимой дате: его ограничивают предшественники или начало проекта.',
  moveBar: 'Перенести работу',
  resizeBar: 'Изменить длительность',
  predecessor: 'Предшественник',
  successor: 'Последователь',
  predecessors: 'Предшествующие задачи',
  successors: 'Последующие задачи',
  addDependency: 'Добавить зависимость',
  deleteDependency: 'Удалить связь',
  searchDependency: 'Поиск работы для связи',
  dependencyDirection: 'Направление связи',
  dependencyWork: 'Работа для связи',
  noPredecessors: 'Предшественников нет.',
  noSuccessors: 'Последователей нет.',
  noCandidates: 'Нет допустимых работ для связи.',
  summaryDependencyHint:
    'Связи разрешены только между конечными работами. Выберите подзадачу.',
  showMore: 'Показать ещё',
  back: 'Назад',
  currentTask: 'Текущая задача',
  openTask: 'Открыть',
  empty: 'В проекте пока нет задач.',
  emptySubtasks: 'Подзадач пока нет.',
  newTask: 'Новая задача',
  addTask: 'Добавить задачу',
  addChild: 'Добавить подзадачу',
  addSibling: 'Добавить соседнюю задачу',
  root: 'Корень проекта',
  parent: 'Родитель',
  quickHint:
    'Enter — добавить соседа · Tab / Shift+Tab — изменить уровень · Esc — выйти из ввода',
  cancel: 'Отмена',
  title: 'Название задачи',
  description: 'Описание',
  status: 'Статус',
  start: 'Начало',
  finish: 'Окончание',
  datesHint:
    'Даты необязательны и сохраняются как введены, без автоматического расчёта.',
  summaryHint: 'Сводная задача: собственные даты не редактируются.',
  save: 'Сохранить',
  saving: 'Сохранение…',
  saved: 'Сохранено',
  dirty: 'Есть несохранённые изменения',
  discard: 'Отбросить изменения',
  close: 'Закрыть панель',
  unsaved: 'Сначала сохраните или отбросьте несохранённые изменения.',
  quickDirty: 'Черновик быстрого ввода',
  clearQuick: 'Очистить быстрый ввод',
  unsavedQuick:
    'В быстром вводе остались несохранённые задачи. Вернитесь к проекту и отправьте или очистите черновик.',
  discardQuickDrafts: 'Отбросить быстрые черновики',
  staleSnapshot:
    'Получен устаревший снимок. Повторите загрузку актуального проекта.',
  retry: 'Повторить',
  retrySave: 'Повторить сохранение',
  network:
    'Нет связи с сервером. Повторите сохранение, когда соединение восстановится.',
  genericError: 'Не удалось выполнить запрос.',
  conflict:
    'Проект изменён в другой сессии. Загрузите актуальный проект; черновик останется в панели.',
  reload: 'Загрузить актуальный проект',
  collapse: 'Свернуть',
  expand: 'Раскрыть',
  delete: 'Удалить ветку',
  deleteConfirm: 'Удалить задачу и все её подзадачи? Изменение можно отменить.',
  preserveConfirm:
    'У задачи есть собственные даты. Добавление первого ребёнка сделает её сводной. Сохранить работу, даты и статус в отдельной подзадаче? Подтвердите, чтобы сохранить работу.',
  undo: 'Отменить последнее изменение',
  undoShort: 'Отменить',
  move: 'Перенести',
  moveParent: 'Новый родитель',
  moveUp: 'Выше',
  moveDown: 'Ниже',
  moveIn: 'Вложить в предыдущую задачу',
  moveOut: 'На уровень выше',
  taskRemoved:
    'Выбранная задача удалена. Черновик сохранён в панели; скопируйте нужные поля или отбросьте изменения.',
  noDate: 'Без дат',
  projectCreated: 'Проект создан.',
  projectCreateUncertain:
    'Ответ не получен. Сначала обновите список проектов, чтобы проверить создание.',
  refreshProjects: 'Обновить список проектов',
  chooseProject: 'Выберите проект.',
} as const;
export const modeLabels = {
  unscheduled: 'Не запланировано',
  auto: 'Автоматический',
  fixed: 'Закреплённый',
} as const;
export const scaleLabels = {
  days: 'Дни',
  weeks: 'Недели',
  months: 'Месяцы',
} as const;
export const calendarLabels = {
  weekdays: 'Пн–пт',
  'all-days': 'Все дни',
} as const;
export const monthLabels = [
  'янв.',
  'фев.',
  'мар.',
  'апр.',
  'мая',
  'июн.',
  'июл.',
  'авг.',
  'сент.',
  'окт.',
  'нояб.',
  'дек.',
] as const;
export const diagnosticLabels: Record<string, string> = {
  LEGACY_INTERVAL_UNAVAILABLE:
    'Прежний интервал недоступен; полный расчёт неизвестен.',
  EXPLICIT_PRECEDENCE_CONFLICT:
    'Предшественник заканчивается после явного начала.',
  UNKNOWN_INTERVAL: 'Полная пара дат не задана.',
  UNKNOWN_PRECEDENCE: 'Интервал связанной задачи неизвестен.',
  INVALID_DURATION: 'Проверьте длительность задачи.',
  INVALID_INTERVAL: 'Проверьте даты и длительность задачи.',
  DURATION_MISMATCH: 'Длительность не совпадает с введёнными датами.',
  INVALID_PRECEDENCE_BOUNDARY: 'Граница связанной задачи недопустима.',
  INVALID_UNAVAILABLE_TASK: 'Не удалось проверить прежний интервал.',
  MISSING_PROJECT_START: strings.missingOrigin,
  BLOCKED_BY_MISSING_PROJECT_START: strings.missingOrigin,
  BLOCKED_BY_UNKNOWN: 'Есть предшественник с неизвестной длительностью.',
  UNKNOWN_DEPENDENCY:
    'Связанная работа не запланирована; зависимая цепь неполная.',
  BLOCKED_BY_INVALID_PREDECESSOR:
    'Недопустимый интервал предшественника блокирует расчёт.',
  FIXED_PRECEDENCE_CONFLICT:
    'Предшественник заканчивается после закреплённого начала.',
  COMPLETED_PRECEDENCE_CONFLICT:
    'Предшественник заканчивается после начала завершённой работы.',
  FIXED_RELEASE_CONFLICT:
    'Закреплённое начало нарушает ограничение «Не раньше».',
  DEADLINE_EXCEEDED: 'Плановое окончание позже дедлайна.',
  INVALID_FIXED_INTERVAL: 'Недопустимый закреплённый интервал.',
  FIXED_BEFORE_PROJECT: 'Закреплённая работа начинается раньше проекта.',
  FIXED_BEFORE_PROJECT_START: 'Закреплённая работа начинается раньше проекта.',
  NON_WORKING_DATE: 'Закреплённая граница приходится на выходной.',
  CALENDAR_RANGE_EXCEEDED: 'План выходит за допустимый диапазон календаря.',
};
export const statusLabels = {
  todo: 'К выполнению',
  doing: 'В работе',
  done: 'Готово',
} as const;
